version: 2.1

defaults: &defaults
  docker:
    - image: cimg/python:2.7-node

jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - run: python --version
      - run: npm install
  test:
    <<: *defaults
    steps:
      - run: npm run test
  lint:
    <<: *defaults
    steps:
      - run: npm run lint

workflows:
  version: 2
  default:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
